Repository bigcommerce/checkout-sdk-js, pull requests merged in 2018-11, with the labels that each got.

#426 CP-4020 Added Product Category to cart & checkout payload
  src/cart/internal-carts.mock.ts
  src/cart/internal-line-item.ts
  src/cart/line-item.ts
  src/cart/line-items.mock.ts
  src/cart/map-to-internal-line-item.ts
  src/checkout/checkout-params.ts
  src/checkout/checkout-service.ts
  src/order/internal-orders.mock.ts
  src/shipping/consignment-action-creator.ts
Labels: sydney

#465 feat(checkout): INT-1073 Populate shipping info from Masterpass on Stripe
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
  src/customer/strategies/masterpass-customer-strategy.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.ts
Labels: integrations, reviewed

#463 fix(payment): INT-1080 Round totalPrice to 2 decimals
  src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
  src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
  src/payment/strategies/googlepay/googlepay.mock.ts
Labels: integrations, reviewed

#468 INT-1092 Braintree merchantId is sent with the wrong name
  src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
  src/payment/strategies/googlepay/googlepay-braintree.ts
  src/payment/strategies/googlepay/googlepay.mock.ts
Labels: integrations, reviewed

#480 fix(payments): INT-1119 Modify approach in Checkout Button Strategies to consume unique ids
  src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
Labels: integrations
