Repository bigcommerce/checkout-sdk-js, pull requests merged in 2019-08, with the labels that each got.

#651 feat(payment): INT-1768 Payment Intent creation refactor
  src/payment/payment-request-sender.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, reviewable, sydney

#637 feat(payment): INT-1736 Add ReferenceId in the jwt to initialize the Cardinal client
  src/payment/strategies/cybersource/cardinal-client.spec.ts
  src/payment/strategies/cybersource/cardinal-client.ts
  src/payment/strategies/cybersource/cardinal.mock.ts
  src/payment/strategies/cybersource/cardinal.ts
  src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
  src/payment/strategies/cybersource/cybersource-payment-strategy.ts
Labels: integrations, reviewed

#677 INT-1811 Cannot place order with CyberSource 3DS
  src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
  src/payment/strategies/cybersource/cybersource-payment-strategy.ts
Labels: integrations, reviewable, sydney

#619 feat(payment): INT-1608 Modify Paypal Payments Pro's strategy for 3DS
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/strategies/cardinal/cardinal-client.spec.ts
  src/payment/strategies/cardinal/cardinal-client.ts
  src/payment/strategies/cardinal/cardinal-script-loader.spec.ts
  src/payment/strategies/cardinal/cardinal-script-loader.ts
  src/payment/strategies/cardinal/cardinal-three-d-secure-flow.spec.ts
  src/payment/strategies/cardinal/cardinal-three-d-secure-flow.ts
  src/payment/strategies/cardinal/cardinal.mock.ts
  src/payment/strategies/cardinal/cardinal.ts
  src/payment/strategies/cardinal/index.ts
  src/payment/strategies/cybersource/cybersource-payment-strategy.spec.ts
  src/payment/strategies/cybersource/cybersource-payment-strategy.ts
  src/payment/strategies/cybersource/index.ts
  src/payment/strategies/paypal/paypal-pro-payment-strategy.spec.ts
  src/payment/strategies/paypal/paypal-pro-payment-strategy.ts
Labels: integrations, reviewed, sydney

#684 fix(payment): INT-1829 Remove error validation if no action code is present
  src/payment/strategies/cardinal/cardinal-client.spec.ts
  src/payment/strategies/cardinal/cardinal-client.ts
Labels: integrations, reviewable, sydney

#685 fix(payment): INT-1836 Update strategy to support 3ds with vaulting
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
  src/payment/strategies/stripev3/stripev3.ts
Labels: integrations, reviewed, sydney
