Repository bigcommerce/checkout-sdk-js, pull requests merged in 2019-04, with the labels that each got.

#552 fix(payment): INT-1412 Fix masterpass submitPayment payload
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.ts
Labels: integrations, reviewed, sydney

#541 feat(checkout): INT-1293 Affirm checkout strategy
  src/common/error/errors/missing-data-error.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/affirm/affirm-payment-strategy.spec.ts
  src/payment/strategies/affirm/affirm-payment-strategy.ts
  src/payment/strategies/affirm/affirm-script-loader.spec.ts
  src/payment/strategies/affirm/affirm-script-loader.ts
  src/payment/strategies/affirm/affirm.mock.ts
  src/payment/strategies/affirm/affirm.ts
  src/payment/strategies/affirm/affirmJs.ts
  src/payment/strategies/affirm/index.ts
Labels: integrations, sydney

#536 feat(checkout): INT-1245 Checkout Using Zip
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/zip/index.ts
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
  src/payment/strategies/zip/zip-script-loader.spec.ts
  src/payment/strategies/zip/zip-script-loader.ts
  src/payment/strategies/zip/zip.mock.ts
  src/payment/strategies/zip/zip.ts
Labels: integrations, reviewed

#554 feat(payment): INT-1398 Add shipping and billing address before Klarna authorization
  src/payment/strategies/klarna/klarna-credit.ts
  src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
  src/payment/strategies/klarna/klarna-payment-strategy.ts
  src/payment/strategies/klarna/klarna.mock.ts
Labels: integrations, mexico, reviewable
