Repository bigcommerce/checkout-sdk-js, pull requests merged in 2020-05, with the labels that each got.

#863 INT-2611 Update the klarna session before the widget is loaded (Klarna V2)
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
Labels: integrations, reviewable, sydney

#849 INT-2497 Add elavon to supported instruments whitelist
  src/payment/instrument/supported-payment-instruments.ts
Labels: integrations, on hold, reviewed, sydney

#868 INT-2612 Vault SEPA accounts
  src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
  src/payment/strategies/adyenv2/adyenv2.mock.ts
Labels: integrations, ready to merge, reviewed, sydney

#843 INT-2577 Create a strategy for Bolt
  src/order/order-request-body.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
  src/payment/strategies/bolt/bolt-payment-strategy.ts
  src/payment/strategies/bolt/index.ts
Labels: integrations, ready to merge, reviewed, sydney

#871 feat(payment): INT-2613 remove receipt_email in stripe-strategy
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
  src/payment/strategies/stripev3/stripev3.mock.ts
Labels: integrations, ready to merge, reviewed, sydney

#883 refactor(payment): INT-2684 Upgrade Adyen Component Library
  src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
  src/payment/strategies/adyenv2/adyenv2-script-loader.ts
  src/payment/strategies/adyenv2/adyenv2.mock.ts
Labels: integrations, ready to merge, reviewed, sydney

#887 fix(payment): INT-2690 Expose AdyenV2 as a valid GooglePay gateway
  src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#888 fix(payment): INT-2691 Remove integrity & crossorigin attributes for AdyenV2
  src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
  src/payment/strategies/adyenv2/adyenv2-script-loader.ts
  src/payment/strategies/adyenv2/adyenv2.mock.ts
Labels: integrations, reviewable, sydney

#837 feat(payment): INT-2541 Add Laybuy strategy
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/laybuy/index.ts
  src/payment/strategies/laybuy/laybuy-payment-strategy.spec.ts
  src/payment/strategies/laybuy/laybuy-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#874 feat(payments): INT-2668 Increase code coverage for adyenv2 payment s…
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2.mock.ts
Labels: integrations, reviewable, sydney

#881 fix(payment): INT-2674 Fix redirect to home on safari
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney
