Repository bigcommerce/checkout-sdk-js, pull requests merged in 2020-03, with the labels that each got.

#737 INT-1434 Support for Klarna V2
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-registry.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/klarnav2/index.ts
  src/payment/strategies/klarnav2/klarna-payments.ts
  src/payment/strategies/klarnav2/klarnav2-payment-initialize-options.ts
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
  src/payment/strategies/klarnav2/klarnav2-script-loader.spec.ts
  src/payment/strategies/klarnav2/klarnav2-script-loader.ts
  src/payment/strategies/klarnav2/klarnav2-window.ts
  src/payment/strategies/klarnav2/klarnav2.mock.ts
Labels: integrations, ready to merge, reviewed, sydney

#797 refactor(payment): INT-2350 Use createFromAction for every payment method
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
  src/payment/strategies/adyenv2/adyenv2.mock.ts
  src/payment/strategies/adyenv2/adyenv2.ts
Labels: integrations, ready to merge, reviewed, sydney

#804 feat(payment): INT-1104 Add GooglePay on Auth.net
  src/checkout-buttons/checkout-button-options.ts
  src/checkout-buttons/create-checkout-button-registry.ts
  src/checkout-buttons/strategies/checkout-button-method-type.ts
  src/checkout-buttons/strategies/googlepay/googlepay-authorizenet-button-strategy.spec.ts
  src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
  src/customer/create-customer-strategy-registry.ts
  src/customer/customer-request-options.ts
  src/customer/strategies/googlepay/googlepay-authorizenet-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-customer-mock.ts
  src/customer/strategies/googlepay/googlepay-customer-strategy.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/googlepay/googlepay-authorizenet-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-authorizenet-initializer.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  src/payment/strategies/googlepay/googlepay.mock.ts
  src/payment/strategies/googlepay/googlepay.ts
  src/payment/strategies/googlepay/index.ts
Labels: integrations, ready to merge, reviewed

#814 fix(payment): INT-2418 Use SecurityNumber as a safeguard
  src/payment/strategies/adyenv2/adyenv2.ts
Labels: integrations, reviewable, sydney

#815 INT-2427 Use ExpiryDate while paying with a vaulted Bancontact card rather than CVV
  src/payment/strategies/adyenv2/adyenv2.ts
Labels: integrations, mexico, reviewable

#817 feat(payment): INT-1710 Add support for ACH & Vipps on Adyen
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
  src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
  src/payment/strategies/adyenv2/adyenv2-script-loader.ts
  src/payment/strategies/adyenv2/adyenv2.ts
Labels: integrations, reviewable, sydney

#823 INT-2001 Enable support for Store Credit on both versions of Klarna
  src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
  src/payment/strategies/klarna/klarna-payment-strategy.ts
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
Labels: integrations, on hold, reviewable, reviewed, sydney

#819 fix(payment): INT-2431 Adds expiration date for Bancontact payments
  src/payment/payment.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Labels: integrations, reviewable, sydney
