Repository bigcommerce/checkout-sdk-js, pull requests merged in 2020-06, with the labels that each got.

#879 INT-2001 Reload widget when apply store credit checkbox state changes
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#878 feat(payment): INT-2629 Relate stripeConnectedAccount while initilaling GooglePay
  src/payment/strategies/googlepay/googlepay-braintree-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-stripe-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
  src/payment/strategies/googlepay/googlepay.mock.ts
Labels: integrations, ready to merge, reviewed, sydney

#894 chore(payment): CHECKOUT-4909 Bump script-loader-js
  package-lock.json
  package.json
Labels: integrations, ready to merge, reviewed, sydney

#902 revert(payment): INT-2726 Revert Fix redirect to home on safari
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
Labels: integrations, reviewable, sydney

#880 fix(common): INT-2308 Align button Tell me more at checkout section
  src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#896 feat(payment): INT-2722 Upgrade Adyen component library
  src/payment/strategies/adyenv2/adyenv2-script-loader.spec.ts
  src/payment/strategies/adyenv2/adyenv2-script-loader.ts
Labels: integrations, ready to merge, reviewed, sydney

#890 refactor(vaulting): INT-2614 renaming values for iban/accountnumber.
  src/payment/instrument/instrument-response-body.ts
  src/payment/instrument/instrument.mock.ts
  src/payment/instrument/instrument.ts
  src/payment/instrument/map-to-account-instrument.ts
Labels: integrations, ready to merge, reviewed, sydney

#898 chore(payment): INT-2280 Bump request-sender-js to v1.0.3
  package-lock.json
  package.json
  src/cart/cart-request-sender.spec.ts
  src/cart/cart-request-sender.ts
  src/cart/index.ts
  src/checkout/checkout-request-sender.spec.ts
  src/checkout/checkout-request-sender.ts
  src/checkout/checkout-store-error-selector.spec.ts
  src/common/error/errors/timeout-error.ts
  src/common/error/errors/unrecoverable-error.ts
  src/common/error/request-error-factory.ts
  src/common/http-request/responses.mock.ts
  src/coupon/gift-certificate-action-creator.spec.ts
  src/customer/customer-action-creator.spec.ts
  src/customer/customer-request-sender.spec.ts
  src/customer/strategies/chasepay/chasepay-customer-strategy.ts
  src/embedded-checkout/embedded-checkout.ts
  src/geography/country-action-creator.spec.ts
  src/geography/country-request-sender.spec.ts
  src/payment/errors/payment-method-invalid-error.ts
  src/payment/instrument/instrument-action-creator.spec.ts
  src/payment/instrument/instrument-request-sender.spec.ts
  src/payment/instrument/instrument-request-sender.ts
  src/payment/payment-request-sender.ts
  src/payment/strategies/cardinal/cardinal-three-d-secure-flow.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
  src/remote-checkout/remote-checkout-request-sender.ts
  src/shipping/shipping-country-action-creator.spec.ts
  src/shipping/shipping-country-request-sender.spec.ts
  src/spam-protection/spam-protection-action-creator.spec.ts
Labels: integrations, ready to merge, reviewed, sydney

#904 fix(payment): INT-2759 Do not mount GiroPay component while initializing payment strategy
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Labels: bug, integrations, ready to merge, reviewed, sydney

#910 docs(payment): INT-2119 Add the @alpha modifier to AmazonPayV2
  src/checkout-buttons/checkout-button-options.ts
  src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts
  src/checkout-buttons/strategies/checkout-button-method-type.ts
  src/customer/customer-request-options.ts
  src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-initialize-options.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
  src/shipping/shipping-request-options.ts
  src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-initialize-options.ts
Labels: integrations, ready to merge, reviewed, sydney

#912 feat(payment): INT-2119 Amazon Pay V2 strategies
  src/checkout-buttons/checkout-button-options.ts
  src/checkout-buttons/create-checkout-button-registry.ts
  src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts
  src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
  src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
  src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button.mock.ts
  src/checkout-buttons/strategies/amazon-pay-v2/index.ts
  src/checkout-buttons/strategies/checkout-button-method-type.ts
  src/checkout/checkout-store-status-selector.spec.ts
  src/checkout/checkout-store-status-selector.ts
  src/customer/create-customer-strategy-registry.ts
  src/customer/customer-request-options.ts
  src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-initialize-options.ts
  src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
  src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
  src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer.mock.ts
  src/customer/strategies/amazon-pay-v2/index.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-script-loader.spec.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-script-loader.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
  src/payment/strategies/amazon-pay-v2/create-amazon-pay-v2-payment-processor.ts
  src/payment/strategies/amazon-pay-v2/index.ts
  src/shipping/create-shipping-strategy-registry.spec.ts
  src/shipping/create-shipping-strategy-registry.ts
  src/shipping/shipping-request-options.ts
  src/shipping/shipping-strategy-action-creator.spec.ts
  src/shipping/shipping-strategy-action-creator.ts
  src/shipping/shipping-strategy-actions.ts
  src/shipping/shipping-strategy-reducer.spec.ts
  src/shipping/shipping-strategy-reducer.ts
  src/shipping/shipping-strategy-selector.spec.ts
  src/shipping/shipping-strategy-selector.ts
  src/shipping/shipping-strategy-state.ts
  src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-initialize-options.ts
  src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.spec.ts
  src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-strategy.ts
  src/shipping/strategies/amazon-pay-v2/index.ts
Labels: integrations, reviewable, sydney

#909 feat(payment): INT-2282 Checkout.com strategies
  src/checkout-buttons/checkout-button-options.ts
  src/checkout-buttons/create-checkout-button-registry.ts
  src/checkout-buttons/strategies/checkout-button-method-type.ts
  src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
  src/checkout-buttons/strategies/googlepay/googlepay-checkoutcom-button-strategy.spec.ts
  src/customer/create-customer-strategy-registry.ts
  src/customer/customer-request-options.ts
  src/customer/strategies/googlepay/googlepay-customer-mock.ts
  src/customer/strategies/googlepay/googlepay-customer-strategy.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/checkoutcom/checkoutcom-googlepay-token.ts
  src/payment/strategies/checkoutcom/checkoutcom-token.ts
  src/payment/strategies/checkoutcom/index.ts
  src/payment/strategies/credit-card-redirect/credit-card-redirect-payment-strategy.spec.ts
  src/payment/strategies/credit-card-redirect/credit-card-redirect-payment-strategy.ts
  src/payment/strategies/credit-card-redirect/index.ts
  src/payment/strategies/credit-card/credit-card-payment-strategy.ts
  src/payment/strategies/googlepay/googlepay-adyenv2-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-adyenv2-initializer.ts
  src/payment/strategies/googlepay/googlepay-authorizenet-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-authorizenet-initializer.ts
  src/payment/strategies/googlepay/googlepay-braintree-initializer.ts
  src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts
  src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  src/payment/strategies/googlepay/googlepay-stripe-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
  src/payment/strategies/googlepay/googlepay.mock.ts
  src/payment/strategies/googlepay/googlepay.ts
  src/payment/strategies/googlepay/index.ts
Labels: integrations, ready to merge, reviewed, sydney
