Repository bigcommerce/checkout-sdk-js, pull requests merged in 2021-12, with the labels that each got.

#1266 feat(payment): INT-4897 Humm - Add Humm strategy as external payment
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/humm/humm-payment-strategy.spec.ts
  src/payment/strategies/humm/humm-payment-strategy.ts
  src/payment/strategies/humm/index.ts
Labels: integrations, sydney, reviewed, ready to merge

#1298 fix(checkout): ADYEN-320 reset adyen component state on deinitialize
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Labels: sydney

#1286 feat(payment): INT-5000 Throw error when payment method isn't available
  src/payment/strategies/digitalriver/digitalriver-error.spec.ts
  src/payment/strategies/digitalriver/digitalriver-error.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1288 test(payment): INT-4926 increase code coverage for GooglePayStrategy
  src/payment/strategies/googlepay/googlepay-adyenv2-payment-processor.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1287 feat(payment): INT-4893 Retrieve initialization data from Humm
  src/payment/create-payment-strategy-registry.ts
  src/payment/errors/index.ts
  src/payment/errors/payment-execute-error.spec.ts
  src/payment/errors/payment-execute-error.ts
  src/payment/strategies/humm/humm-payment-strategy.spec.ts
  src/payment/strategies/humm/humm-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1302 fix(payment): INT-5166 CKO mapping for vaulted instrument
  src/payment/instrument/supported-payment-instruments.ts
Labels: integrations, sydney, reviewed, ready to merge, important
