Repository bigcommerce/checkout-sdk-js, pull requests merged in 2021-08, with the labels that each got.

#1174 fix(payment): INT-4481 GooglePay: Fix issue when attempting to pay without a last name provided in the billing address
  src/payment/strategies/googlepay/googlepay-get-first-and-last-name.spec.ts
  src/payment/strategies/googlepay/googlepay-get-first-and-last-name.ts
  src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
Labels: integrations, ready to merge, reviewed, sydney

#1172 docs(payment): INT-4144 Add Documentation for Moneris
  src/payment/strategies/moneris/moneris-payment-initialize-options.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
  src/payment/strategies/moneris/moneris.ts
Labels: integrations, ready to merge, reviewed, sydney

#1194 fix(provider): INT-4480 Throws stripe error when user closes the auth modal on Stripe V3
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
  src/payment/strategies/stripev3/stripev3.ts
Labels: integrations, ready to merge, reviewed, sydney

#1187 feat(payment): INT-4584 - Refactor Quadpay uri data for redirect
  src/payment/payment-methods.mock.ts
  src/payment/strategies/quadpay/quadpay-payment-strategy.spec.ts
  src/payment/strategies/quadpay/quadpay-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1185 feat(payment): INT-4585 - Refactor Zip uri data for redirect
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1165 fix(payment): INT-4438 update SDK documentation for Digital River
  src/payment/strategies/digitalriver/digitalriver-payment-initialize-options.ts
Labels: integrations, ready to merge, reviewed, sydney

#1197 fix(payment): INT-3946 using supported locales on masterpass SRC
  src/checkout-buttons/checkout-button-initializer-options.ts
  src/checkout-buttons/checkout-button-initializer.spec.ts
  src/checkout-buttons/create-checkout-button-initializer.ts
  src/checkout-buttons/create-checkout-button-registry.spec.ts
  src/checkout-buttons/create-checkout-button-registry.ts
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.spec.ts
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
  src/checkout/checkout-service.spec.ts
  src/checkout/create-checkout-service.ts
  src/customer/create-customer-strategy-registry.ts
  src/customer/customer-strategy-action-creator.spec.ts
  src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.spec.ts
  src/customer/strategies/masterpass/masterpass-customer-strategy.spec.ts
  src/customer/strategies/masterpass/masterpass-customer-strategy.ts
  src/locale/language-service.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/masterpass/format-locale.spec.ts
  src/payment/strategies/masterpass/format-locale.ts
  src/payment/strategies/masterpass/index.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.ts
  src/payment/strategies/masterpass/masterpass-supported-locales.ts
Labels: integrations, sydney, reviewed, ready to merge

#1170 feat(payment): BOLT-30 updated finalize method for Bolt payment strategy
  src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
  src/payment/strategies/bolt/bolt-payment-strategy.ts
  src/payment/strategies/bolt/bolt-script-loader.ts
  src/payment/strategies/bolt/bolt.mock.ts
  src/payment/strategies/bolt/bolt.ts
Labels: sydney, reviewable

#1190 feat(payment): INT-4592 Added 3DS handler to SquareV2
  src/payment/strategies/square/square-form.ts
  src/payment/strategies/square/square-payment-strategy.spec.ts
  src/payment/strategies/square/square-payment-strategy.ts
  src/payment/strategies/square/square-script-loader.spec.ts
  src/payment/strategies/square/square-script-loader.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1203 feat(payment): INT-4222 Add vaulting compatibility to Moneris
  src/payment/create-payment-strategy-registry.ts
  src/payment/index.ts
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/is-hosted-intrument-like.spec.ts
  src/payment/is-hosted-intrument-like.ts
  src/payment/payment-methods.mock.ts
  src/payment/strategies/moneris/moneris-payment-initialize-options.ts
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
  src/payment/strategies/moneris/moneris.mock.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1159 fix(analytics): DATA-7883 Fix Segment + GAEE issue
  src/analytics/analytics-step-tracker.spec.ts
  src/analytics/analytics-step-tracker.ts
  src/analytics/analytics-tracker-ga.spec.ts
  src/analytics/analytics-tracker-ga.ts
  src/analytics/analytics-tracker-window.ts
Labels: sydney

#1206 feat(checkout): PAYPAL-1100 added paylater to enable-funding field on paypalcommerce checkout and buttons
  src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
  src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Labels: sydney

#1177 feat(payment): INT-4456 Add CA/FR to klarna countries list
  src/payment/strategies/klarnav2/klarna-supported-countries.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1192 fix(payment): INT-4672 Allow shoppers to change payment method when order finalization fails
  src/order/errors/index.ts
  src/order/errors/order-finalization-not-completed-error.spec.ts
  src/order/errors/order-finalization-not-completed-error.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
  src/payment/strategies/afterpay/afterpay-payment-strategy.ts
  src/remote-checkout/remote-checkout-request-sender.spec.ts
  src/remote-checkout/remote-checkout-request-sender.ts
Labels: integrations, sydney, reviewed, ready to merge

#1218 fix(payment): BOLT-47 fixed an issue of throwing payment method error…
  src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
  src/payment/strategies/bolt/bolt-payment-strategy.ts
  src/payment/strategies/bolt/bolt-script-loader.spec.ts
  src/payment/strategies/bolt/bolt-script-loader.ts
Labels: sydney, reviewable

#1213 fix(payment): INT-4594 [Afterpay] display correct error message when amount is out of limits
  src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
  src/payment/strategies/afterpay/afterpay-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1214 feat(payment): INT-4141 Improve css look and feel
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
  src/payment/strategies/moneris/moneris.ts
Labels: integrations, sydney, reviewed, ready to merge, important
