Repository bigcommerce/checkout-sdk-js, pull requests merged in 2021-05, with the labels that each got.

#1127 feat(payment): INT-4258 StripeV3: Improve error handling
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
  src/payment/strategies/stripev3/stripev3.ts
Labels: integrations, ready to merge, reviewed, sydney

#1126 feat(payment): INT-4237 Add issuer for Mollie APMs
  src/order/order-request-body.ts
  src/payment/index.ts
  src/payment/payment.ts
  src/payment/strategies/klarnav2/klarna-supported-countries.ts
  src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  src/payment/strategies/mollie/mollie-payment-strategy.ts
  src/payment/strategies/mollie/mollie.mock.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1121 feat(payment): INT-4071 Clearpay - Create custom strategy
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/clearpay/clearpay-payment-strategy.spec.ts
  src/payment/strategies/clearpay/clearpay-payment-strategy.ts
  src/payment/strategies/clearpay/clearpay-script-loader.spec.ts
  src/payment/strategies/clearpay/clearpay-script-loader.ts
  src/payment/strategies/clearpay/clearpay-sdk.ts
  src/payment/strategies/clearpay/clearpay-window.ts
  src/payment/strategies/clearpay/clearpay.mock.ts
  src/payment/strategies/clearpay/index.ts
Labels: integrations, ready to merge, reviewed, sydney

#1130 fix(checkout): INT-3941 Updated remote-checkout path on button initialization
  src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1105 feat(payment): PAYPAL-976 Order placement v2
  src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-initialize-options.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
  src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Labels: sydney

#1142 feat(checkout): PAYPAL-1024 make APM work regardless of geolocation
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
Labels: sydney

#1141 feat(payment): INT-4197 added type and color parameters on googlepay checkout button
  src/checkout-buttons/checkout-button-options.ts
  src/checkout-buttons/strategies/googlepay/googlepay-adyenv2-button-strategy.spec.ts
  src/checkout-buttons/strategies/googlepay/googlepay-authorizenet-button-strategy.spec.ts
  src/checkout-buttons/strategies/googlepay/googlepay-braintree-button-strategy.spec.ts
  src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
  src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
  src/checkout-buttons/strategies/googlepay/googlepay-checkoutcom-button-strategy.spec.ts
  src/checkout-buttons/strategies/googlepay/googlepay-cybersourcev2-button-strategy.spec.ts
  src/checkout-buttons/strategies/googlepay/googlepay-stripe-button-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-customer-initialize-options.ts
  src/customer/strategies/googlepay/googlepay-customer-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1145 feat(payment): INT-4310 Update DR strategy to support vaulted instruments
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
Labels: integrations, ready to merge, reviewed

#1129 feat(payment): INT-4242 Add Quadpay payment strategy
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/index.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-strategy-type.ts
  src/payment/storefront-payment-request-sender.spec.ts
  src/payment/storefront-payment-request-sender.ts
  src/payment/strategies/quadpay/index.ts
  src/payment/strategies/quadpay/quadpay-payment-strategy.spec.ts
  src/payment/strategies/quadpay/quadpay-payment-strategy.ts
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney
