Repository bigcommerce/checkout-sdk-js, pull requests merged in 2021-03, with the labels that each got.

#1053 feat(checkout): INT-3675 Add Bolt's tracking script to checkout
  src/payment/strategies/bolt/bolt-script-loader.spec.ts
  src/payment/strategies/bolt/bolt-script-loader.ts
Labels: integrations, ready to merge, reviewable, sydney

#1072 feat(payment): INT-3408 migrate masterpass to SRC
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.spec.ts
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
  src/customer/strategies/masterpass/masterpass-customer-strategy.spec.ts
  src/customer/strategies/masterpass/masterpass-customer-strategy.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.ts
  src/payment/strategies/masterpass/masterpass-script-loader.ts
Labels: integrations, ready to merge, reviewed, sydney

#1052 feat(payments): INT-3610 added Mollie Checkout
  src/payment/create-payment-strategy-registry.ts
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/mollie/index.ts
  src/payment/strategies/mollie/mollie-initialize-options.ts
  src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  src/payment/strategies/mollie/mollie-payment-strategy.ts
  src/payment/strategies/mollie/mollie-script-loader.ts
  src/payment/strategies/mollie/mollie.mock.ts
  src/payment/strategies/mollie/mollie.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1066 feat(checkout): INT-3700 Load Bolt Scripts from different environments
  src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
  src/payment/strategies/bolt/bolt-payment-strategy.ts
  src/payment/strategies/bolt/bolt-script-loader.spec.ts
  src/payment/strategies/bolt/bolt-script-loader.ts
  src/payment/strategies/bolt/bolt.ts
Labels: integrations, ready to merge, reviewed, sydney

#1076 INT-3840 Create Digital River boilerplate
  src/common/error/errors/missing-data-error.ts
  src/customer/customer-selector.ts
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/digitalriver/digitalriver-payment-initialize-options.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
  src/payment/strategies/digitalriver/digitalriver-script-loader.spec.ts
  src/payment/strategies/digitalriver/digitalriver-script-loader.ts
  src/payment/strategies/digitalriver/digitalriver.mock.ts
  src/payment/strategies/digitalriver/digitalriver.ts
  src/payment/strategies/digitalriver/index.ts
Labels: integrations, ready to merge, reviewed, sydney

#1075 feat(payment): INT-3896 [Zip] it returns the nonce value when it's a referred payment
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1078 fix(checkout): INT-2546 Add ideal to document supported apms
  src/payment/strategies/checkoutcom-apm/checkoutcom-apm-payment-strategy.ts
Labels: important, ready to merge, reviewed, sydney

#1086 feat(payment): INT-3947 Suppress PayPal and Klarna
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
  src/payment/strategies/digitalriver/digitalriver.ts
Labels: integrations, ready to merge, reviewed, sydney

#1087 feat(payment): INT-3905 creating execute for digital river and creditCard
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1089 fix(provider): INT-3571 Google Pay [StripeV3] - Billing address is missing
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
  src/payment/strategies/googlepay/googlepay.mock.ts
Labels: integrations, ready to merge, reviewed, sydney
