Repository bigcommerce/checkout-sdk-js, pull requests merged in 2021-04, with the labels that each got.

#1079 feat(payment): INT-3931 Add strategy for checkout.com with SEPA
  src/order/order-request-body.ts
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/index.ts
  src/payment/payment-strategy-registry.ts
  src/payment/payment-strategy-type.ts
  src/payment/payment.ts
  src/payment/strategies/checkoutcom-apm/index.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-apm/checkoutcom-apm-payment-strategy.spec.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-apm/checkoutcom-apm-payment-strategy.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-custom-payment-strategy.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-sepa/checkoutcom-sepa-payment-strategy.spec.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-sepa/checkoutcom-sepa-payment-strategy.ts
  src/payment/strategies/checkoutcom-custom/index.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1094 fix(payment): INT-3408 added masterpass SRC experiment
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.spec.ts
  src/checkout-buttons/strategies/masterpass/masterpass-button-strategy.ts
  src/customer/strategies/masterpass/masterpass-customer-strategy.spec.ts
  src/customer/strategies/masterpass/masterpass-customer-strategy.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.spec.ts
  src/payment/strategies/masterpass/masterpass-payment-strategy.ts
  src/payment/strategies/masterpass/masterpass-script-loader.ts
Labels: integrations, ready to merge, reviewed, sydney

#1106 Support coupons & gift cards codes when the Drop-in component is already loaded for Digital River
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
  src/payment/strategies/digitalriver/digitalriver-script-loader.spec.ts
  src/payment/strategies/digitalriver/digitalriver-script-loader.ts
  src/payment/strategies/digitalriver/digitalriver.ts
Labels: integrations, ready to merge, reviewed, sydney

#1102 feat(payment): INT-4021 Add strategy for iDeal APM
  src/order/order-request-body.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/index.ts
  src/payment/payment-strategy-registry.ts
  src/payment/payment-strategy-type.ts
  src/payment/payment.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-ideal/checkoutcom-ideal-payment-strategy.spec.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-ideal/checkoutcom-ideal-payment-strategy.ts
  src/payment/strategies/checkoutcom-custom/index.ts
Labels: integrations, ready to merge, reviewed, sydney

#1056 feat(payment): INT-3702 added vaulted cc
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/strategies/mollie/mollie-initialize-options.ts
  src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  src/payment/strategies/mollie/mollie-payment-strategy.ts
  src/payment/strategies/mollie/mollie.mock.ts
  src/payment/strategies/mollie/mollie.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1082 fix(payment): INT-3611 Refresh the state in Googlepay and Braintree r…
  src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  src/payment/strategies/googlepay/googlepay.mock.ts
Labels: integrations, reviewed, sydney

#1080 feat(payment): INT-2503 Add strategy for checkout.com with Fawry
  src/order/order-request-body.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/index.ts
  src/payment/payment-strategy-registry.ts
  src/payment/payment-strategy-type.ts
  src/payment/payment.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-sepa/checkoutcom-fawry-payment-strategy.spec.ts
  src/payment/strategies/checkoutcom-custom/checkoutcom-sepa/checkoutcom-fawry-payment-strategy.ts
  src/payment/strategies/checkoutcom-custom/index.ts
Labels: integrations, ready to merge, reviewed, sydney

#1113 feat(payment): INT-3702 Add vaulted credit card support for Mollie
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/strategies/mollie/mollie-initialize-options.ts
  src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  src/payment/strategies/mollie/mollie-payment-strategy.ts
  src/payment/strategies/mollie/mollie.mock.ts
  src/payment/strategies/mollie/mollie.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1104 fix(payment): INT-4063 Avoid holding inventory if a payment intent co…
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
  src/payment/strategies/stripev3/stripev3.mock.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1118 feat(payments): INT-4150 changing zip strategy flow
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1122 fix(payment): INT-4266 Googlepay - fixing where nonce value is going …
  src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
Labels: integrations, ready to merge, reviewed
