Repository bigcommerce/checkout-sdk-js, pull requests merged in 2021-09, with the labels that each got.

#1230 fix(checkout): ADYEN-231 fixed adyen checkout form localization
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
Labels: sydney

#1204 fix(payment): INT-4705 [Clearpay] display correct error message when amount is out of limits
  src/payment/strategies/clearpay/clearpay-payment-strategy.spec.ts
  src/payment/strategies/clearpay/clearpay-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1234 fix(payment): INT-4810 Forget checkout provider and reload payment methods - Clearpay
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/clearpay/clearpay-payment-strategy.spec.ts
  src/payment/strategies/clearpay/clearpay-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1235 feat(payment): BOLT-24 added account creation flag for Bolt Embedded One Click execution
  src/customer/strategies/bolt/bolt-customer-strategy.ts
  src/order/order-request-body.ts
  src/payment/index.ts
  src/payment/payment.ts
  src/payment/strategies/bolt/bolt-payment-initialize-options.ts
  src/payment/strategies/bolt/bolt-payment-strategy.spec.ts
  src/payment/strategies/bolt/bolt-payment-strategy.ts
  src/payment/strategies/bolt/bolt.ts
  src/payment/strategies/braintree/braintree-paypal-payment-strategy.ts
  src/payment/with-account-creation.ts
Labels: sydney, reviewable

#1228 fix(payment): INT-4802 Moneris Validate response before resolve
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1223 fix(checkout): INT-4798 Fix Moneris Hosted Field Validation
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1215 fix(payment): INT-4674 Using forgetCheckout instead of signOut on Google Pay
  src/customer/create-customer-strategy-registry.ts
  src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
  src/customer/strategies/amazon/amazon-pay-customer-strategy.spec.ts
  src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.spec.ts
  src/customer/strategies/chasepay/chasepay-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-adyenv2-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-authorizenet-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-braintree-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-checkoutcom-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-customer-strategy.ts
  src/customer/strategies/googlepay/googlepay-cybersourcev2-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-orbital-customer-strategy.spec.ts
  src/customer/strategies/googlepay/googlepay-stripe-customer-strategy.spec.ts
  src/customer/strategies/masterpass/masterpass-customer-strategy.spec.ts
  src/customer/strategies/square/square-customer-strategy.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
  src/payment/strategies/klarna/klarna-payment-strategy.spec.ts
  src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
  src/payment/strategies/quadpay/quadpay-payment-strategy.spec.ts
  src/payment/strategies/zip/zip-payment-strategy.spec.ts
  src/remote-checkout/remote-checkout-action-creator.spec.ts
  src/remote-checkout/remote-checkout-action-creator.ts
  src/remote-checkout/remote-checkout-actions.ts
  src/shipping/create-shipping-strategy-registry.ts
  src/shipping/strategies/amazon/amazon-pay-shipping-strategy.spec.ts
Labels: integrations, sydney, reviewed, ready to merge

#1242 feat(checkout): CHECKOUT-5777 Send SDK version as a header for all SDK API requests
  src/billing/billing-address-request-sender.spec.ts
  src/billing/billing-address-request-sender.ts
  src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
  src/checkout-buttons/strategies/paypal/paypal-button-strategy.ts
  src/checkout/checkout-request-sender.spec.ts
  src/checkout/checkout-request-sender.ts
  src/common/http-request/index.ts
  src/common/http-request/sdk-version-headers.ts
  src/config/config-request-sender.spec.ts
  src/config/config-request-sender.ts
  src/coupon/coupon-request-sender.spec.ts
  src/coupon/coupon-request-sender.ts
  src/coupon/gift-certificate-request-sender.spec.ts
  src/coupon/gift-certificate-request-sender.ts
  src/customer/customer-request-sender.spec.ts
  src/customer/customer-request-sender.ts
  src/customer/strategies/chasepay/chasepay-customer-strategy.ts
  src/customer/strategies/googlepay/googlepay-customer-strategy.ts
  src/form/form-fields-request-sender.spec.ts
  src/form/form-fields-request-sender.ts
  src/geography/country-request-sender.spec.ts
  src/geography/country-request-sender.ts
  src/order/order-request-sender.spec.ts
  src/order/order-request-sender.ts
  src/payment/payment-method-request-sender.spec.ts
  src/payment/payment-method-request-sender.ts
  src/payment/storefront-payment-request-sender.spec.ts
  src/payment/storefront-payment-request-sender.ts
  src/payment/strategies/braintree/braintree-visacheckout-payment-processor.ts
  src/payment/strategies/braintree/visacheckout.mock.ts
  src/payment/strategies/chasepay/chasepay-payment-strategy.ts
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-request-sender.ts
  src/payment/strategies/square/square-payment-strategy.ts
  src/remote-checkout/remote-checkout-request-sender.spec.ts
  src/remote-checkout/remote-checkout-request-sender.ts
  src/shipping/consignment-request-sender.spec.ts
  src/shipping/consignment-request-sender.ts
  src/shipping/shipping-country-request-sender.spec.ts
  src/shipping/shipping-country-request-sender.ts
  src/signin-email/signin-email-request-sender.spec.ts
  src/signin-email/signin-email-request-sender.ts
  src/spam-protection/spam-protection-request-sender.spec.ts
  src/spam-protection/spam-protection-request-sender.ts
  src/store-credit/store-credit-request-sender.spec.ts
  src/store-credit/store-credit-request-sender.ts
  src/subscription/subscriptions-request-sender.spec.ts
  src/subscription/subscriptions-request-sender.ts
Labels: ready to merge

#1244 fix(checkout): ADYEN-260 fixed googlepay updates billing info by removing customer email update
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
Labels: sydney

#1248 Revert "fix(checkout): ADYEN-260 fixed googlepay updates billing info by removing customer email update"
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
Labels: integrations, mexico, reviewable

#1179 feat(payment): INT-4170 added hosted fields on verification fields
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/strategies/stripev3/stripev3-initialize-options.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
  src/payment/strategies/stripev3/stripev3.mock.ts
Labels: integrations, sydney, reviewed, ready to merge

#1232 fix(payment): INT-4698 VISA Checkout load payment information
  src/customer/create-customer-strategy-registry.ts
  src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.spec.ts
  src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1240 feat(payment): PAYPAL-972 added threeDSecure check for googlepaybraintree
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/braintree/braintree.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  src/payment/strategies/googlepay/googlepay.ts
Labels: sydney

#1202 fix(payment): INT-4489 cko add supported method 'card'
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/payment-strategy-registry.ts
Labels: integrations, sydney, reviewed, ready to merge

#1196 fix(payment): INT-4087 Catch stripe exception to process 3ds when payment intent is updated on the backend - StripeV3
  src/payment/payment-methods.mock.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1245 feat(payment): PAYPAL-1103 added pay later messaging on cart
  src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
  src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
  src/payment/strategies/braintree/braintree-sdk-creator.ts
  src/payment/strategies/braintree/braintree.ts
  src/payment/strategies/paypal/paypal-express-payment-strategy.spec.ts
  src/payment/strategies/paypal/paypal-sdk.ts
  src/payment/strategies/paypal/paypal.mock.ts
Labels: sydney

#1251 fix(checkout): ADYEN-260 fixed googlepay updates billing info, removed update of customer email
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
Labels: sydney
