Repository bigcommerce/checkout-sdk-js, pull requests merged in 2021-07, with the labels that each got.

#1160 INT 4309 Adding support to Vaulted Cards that requires 3DS and 3DS2 in Digital River
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
  src/payment/strategies/digitalriver/digitalriver.mock.ts
  src/payment/strategies/digitalriver/digitalriver.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1156 feat(payment): INT-4423 Set labels to Moneris iframe creation process
  src/payment/payment-methods.mock.ts
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
  src/payment/strategies/moneris/moneris.ts
Labels: integrations, ready to merge, reviewed, sydney

#1167 fix(payment): INT-4448 Braintree cardTypeChange event
  src/payment/strategies/braintree/braintree-hosted-form.spec.ts
  src/payment/strategies/braintree/braintree-hosted-form.ts
Labels: integrations, ready to merge, reviewed, sydney

#1169 fix(payment): PAYPAL-1026 fixed button height
  src/checkout-buttons/strategies/braintree/braintree-paypal-button-options.ts
  src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
  src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
  src/payment/strategies/paypal/paypal-sdk.ts
Labels: sydney

#1164 INT-4087 Send the client token back to update the payment intent related for StripeV3
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1171 feat(payment): INT-4141 Make iframe border and background transparent
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1191 feat(payment): PAYPAL-1090 added size property for paypalexpress button
  src/checkout-buttons/strategies/paypal/paypal-button-strategy.ts
Labels: sydney

#1184 feat(checkout): PAYPAL-1057 added Venmo APM to paypal commerce
  src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-funding-key-resolver.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
  src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Labels: sydney

#1186 fix(payment): INT-4661 [Afterpay] get countryCode by shopperCurrency
  src/payment/strategies/afterpay/afterpay-payment-strategy.spec.ts
  src/payment/strategies/afterpay/afterpay-payment-strategy.ts
Labels: integrations, ready to merge, reviewed, sydney

#1178 fix(payment): INT-4598 handle vaulting Enable checkbox
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1151 feat(payment): INT-4222 Add vaulting compatibility to Moneris
  src/hosted-form/hosted-form-options.ts
  src/hosted-form/index.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/payment-methods.mock.ts
  src/payment/strategies/moneris/moneris-payment-initialize-options.ts
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
  src/payment/strategies/moneris/moneris.mock.ts
Labels: important, integrations, ready to merge, reviewed, sydney

#1200 fix(payment): INT-4685 Orbital initializer added properly
  src/checkout-buttons/create-checkout-button-registry.ts
Labels: integrations, ready to merge, reviewed, sydney
