Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-08, with the labels that each got.

#1512 feat(payment): ADYEN-539 added vaulting card validation
  packages/core/src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
  packages/core/src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
  packages/core/src/payment/strategies/adyenv2/adyenv2.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3-initialize-options.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3.ts
Labels: sydney

#1498 fix(payment): STRIPE-51 set a stored card as default during checkout
  packages/core/src/payment/payment.ts
  packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1502 feat(payment): INT-6128 AmazonPayV2: Introduce the new API V2 config
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
  packages/core/src/payment/payment-methods.mock.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
Labels: integrations, sydney, reviewed, ready to merge

#1510 fix(payment): INT-5854 [Mollie] Klarna is not available if cart contains digital products
  packages/core/src/payment/strategies/mollie/mollie-initialize-options.ts
  packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
  packages/core/src/payment/strategies/mollie/mollie.mock.ts
Labels: integrations, sydney, reviewable

#1489 feat(customer): INT-6023 Resize VCO button for Discover cards
  packages/core/src/customer/strategies/braintree/braintree-visacheckout-customer-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1556 docs(payment): INT-0000: Add missing backticks
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts
  packages/core/src/payment/strategies/bluesnapv2/bluesnapv2-payment-options.ts
  packages/core/src/payment/strategies/mollie/mollie-initialize-options.ts
Labels: integrations, sydney, reviewed, ready to merge

#1491 feat(payment): INT-6115 Worldpay - 3DS support for Access Worldpay
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/payment-request-options.ts
  packages/core/src/payment/payment-strategy-type.ts
  packages/core/src/payment/strategies/worldpay/index.ts
  packages/core/src/payment/strategies/worldpayaccess/index.ts
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-options.ts
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1522 feat(payment): INT-6342 fix klarna issue adding klarna v1 payment_method
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/strategies/klarnav2/index.ts
  packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.ts
  packages/core/src/payment/strategies/klarnav2/klarnav2-token-updater.spec.ts
  packages/core/src/payment/strategies/klarnav2/klarnav2-token-updater.ts
Labels: bug, integrations, sydney, reviewable

#1488 Fix(payment): STRIPE-53 Give more information on payment authentication with 3ds failure error message
  packages/core/src/payment/strategies/stripev3/stripev3-error.spec.ts
  packages/core/src/payment/strategies/stripev3/stripev3-error.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
  packages/core/src/payment/strategies/stripev3/stripev3.ts
Labels: integrations, sydney, reviewed, ready to merge

#1558 fix(payment): INT-6392 [Mollie] Klarna shopper are able to place orders with digital items through klarna pay later and slice it when them are added via coupon
  packages/core/src/payment/strategies/mollie/mollie-initialize-options.ts
  packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1581 chore(payment): INT-6510 Increase code coverage on BlueSnapV2PaymentStrategy
  packages/core/src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.spec.ts
Labels: integrations, sydney, reviewed, ready to merge

#1565 fix(payment): STRIPE-130 Stripe UPE making postal code not always required to make purchase
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1555 feat(payment): INT-6407 AmazonPayV2: Add the new `estimatedOrderAmount` parameter
  packages/core/src/payment/create-payment-strategy-registry.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
  packages/core/src/payment/strategies/amazon-pay-v2/create-amazon-pay-v2-payment-processor.spec.ts
Labels: integrations, sydney, reviewed, ready to merge, important
