Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-02, with the labels that each got.

#1328 fix(checkout) INT-5409: Change error message when payment data is unavailable
  src/payment/strategies/opy/opy-payment-error.spec.ts
  src/payment/strategies/opy/opy-payment-error.ts
  src/payment/strategies/opy/opy-payment-strategy.spec.ts
  src/payment/strategies/opy/opy-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1331 feat(provider): INT-4969 add 3DS2 flow under experiment for Opayo
  src/payment/payment.ts
  src/payment/strategies/sage-pay/sage-pay-payment-strategy.spec.ts
  src/payment/strategies/sage-pay/sage-pay-payment-strategy.ts
Labels: integrations, reviewed, ready to merge, important

#1220 feat(order): INT-4776 Create a new field for the mandate reference ID
  src/order/order.ts
Labels: integrations, reviewed, ready to merge

#1263 feat(payment): INT-4282 removing masterpass logic for square
  src/payment/strategies/square/square-form.ts
  src/payment/strategies/square/square-payment-initialize-options.ts
  src/payment/strategies/square/square-payment-strategy-mock.ts
  src/payment/strategies/square/square-payment-strategy.spec.ts
  src/payment/strategies/square/square-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1344 feat(payment): INT-5384 Openpay: Add the learn more button widget
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-options.ts
  src/payment/strategies/opy/index.ts
  src/payment/strategies/opy/opy-library.ts
  src/payment/strategies/opy/opy-payment-initialize-options.ts
  src/payment/strategies/opy/opy-payment-strategy.spec.ts
  src/payment/strategies/opy/opy-payment-strategy.ts
  src/payment/strategies/opy/opy-script-loader.spec.ts
  src/payment/strategies/opy/opy-script-loader.ts
  src/payment/strategies/opy/opy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1330 feat(payment): PAYPAL-1282 New style object for PayPal APMs
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Labels: sydney

#1346 feat(payment): PAYPAL-1151 braintree venmo spb integration
  src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
  src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
  src/checkout-buttons/strategies/checkout-button-method-type.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-transformer.spec.ts
  src/payment/payment-request-transformer.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/braintree/braintree-script-loader.ts
  src/payment/strategies/braintree/braintree-sdk-creator.ts
  src/payment/strategies/braintree/braintree.mock.ts
  src/payment/strategies/braintree/braintree.ts
Labels: sydney

#1351 feat(payment): INT-5156 Klarna add support for poland, portugal, ireland
  src/payment/strategies/klarnav2/klarna-supported-countries.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1342 feat(payment): INT-5090 Stripe UPE add return url for SOFORT support
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge
