Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-10, with the labels that each got.

#1598 feat(payment): INT-6297 BNZ GooglePay
  packages/core/src/checkout-buttons/checkout-button-options.ts
  packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts
  packages/core/src/checkout-buttons/create-checkout-button-registry.ts
  packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
  packages/core/src/checkout-buttons/strategies/googlepay/googlepay-bnz-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
  packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
  packages/core/src/customer/create-customer-strategy-registry.ts
  packages/core/src/customer/customer-request-options.ts
  packages/core/src/customer/strategies/googlepay/googlepay-bnz-customer-strategy.spec.ts
  packages/core/src/customer/strategies/googlepay/googlepay-customer-method-type.ts
  packages/core/src/customer/strategies/googlepay/googlepay-customer-mock.ts
  packages/core/src/customer/strategies/googlepay/googlepay-customer-strategy.ts
  packages/core/src/payment/create-payment-strategy-registry.spec.ts
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/payment-request-options.ts
  packages/core/src/payment/payment-strategy-type.ts
  packages/core/src/payment/strategies/googlepay/googlepay-bnz-initializer.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-bnz-initializer.ts
  packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  packages/core/src/payment/strategies/googlepay/googlepay.mock.ts
  packages/core/src/payment/strategies/googlepay/index.ts
Labels: integrations, sydney, reviewable, important

#1605 feat(payment): INT-6092 AmazonPayV2: Add an additional payment button…
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.mock.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
  packages/payment-integration-api/src/config/index.ts
  packages/payment-integration-api/src/index.ts
Labels: integrations, sydney, reviewable, important

#1607 feat(payment): PAYPAL-1606 Added Shipping options for paypal and updated paypal callbacks
  packages/core/src/checkout-buttons/create-checkout-button-registry.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-options.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.spec.ts
  packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Labels: sydney

#1610 feat(payment): PAYPAL-1607 added shipping Options for paypal credit and updated paypal callbacks
  packages/core/src/checkout-buttons/create-checkout-button-registry.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-alternative-methods-button-strategy.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-options.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-venmo-button-strategy.ts
  packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
  packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
  packages/core/src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
Labels: sydney

#1591 feat(payment): STRIPE-99 Add flag to validate unmount
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1618 fix(payment): INT-6478 SquareV2 - Fail Gracefully when payment provider unavailable
  packages/core/src/payment/strategies/square/square-payment-strategy.ts
  packages/core/src/payment/strategies/square/square-script-loader.ts
Labels: integrations, sydney, reviewed, ready to merge

#1611 fix(payment): INT-6539 GooglePay: Pass `hostname` as param when loadi…
  packages/core/src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-payment-processor.ts
Labels: integrations, sydney, reviewed, ready to merge

#1647 fix(payment): INT-6772 WorldpayAcces supported in firefox
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1632 feat(payment): INT-6675 [Digital River] Update billingAddress from paypal
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
  packages/core/src/payment/strategies/digitalriver/digitalriver.ts
Labels: integrations, sydney, reviewed, ready to merge
