Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-11, with the labels that each got.

#1655 fix(payment): INT-6848 AmazonPayV2: Render the button in a container created programmatically
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1671 feat(payment): INT-5953-T Force to use Payment Strategy V1 when Mollie and Apple pay
  packages/core/src/payment/payment-strategy-action-creator.spec.ts
  packages/core/src/payment/payment-strategy-action-creator.ts
Labels: integrations, mexico, reviewable

#1669 fix(payment): INT-6890 AmazonPayV2: Change `isReadyToPay` logic
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1649 feat(payment): STRIPE-183 persisting stripe components when reloads the page
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.spec.ts
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.ts
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-initialize-options.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
Labels: integrations, sydney, reviewable, qa pending, important

#1667 feat(payment): PAYPAL-1722 added skip checkout functionality to PDP
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-button-strategy.ts
Labels: sydney

#1615 fix(payment): STRIPE-167 Adding Postal Code to stripe card element if not obtained in billing
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1643 feat(payment): INT-6443 Hide payPal onDigital River behind an experiment
  packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.spec.ts
  packages/core/src/payment/strategies/digitalriver/digitalriver-payment-strategy.ts
  packages/core/src/payment/strategies/digitalriver/digitalriver.ts
Labels: integrations, sydney, reviewed, ready to merge

#1678 feat(payment): PAYPAL-1723 added ability to skip checkout page on PDP (paypalcommercecredit)
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/paypal-commerce/paypal-commerce-credit-button-strategy.ts
Labels: sydney

#1695 fix(payment): STRIPE-167 Adding Postal Code to stripe card element if not obtained in billing
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1642 feat(payment): INT-6716 SquareV2: Add payment strategy
  package-lock.json
  package.json
  packages/payment-integration-api/src/errors/payment-method-client-unavailable-error.spec.ts
  packages/payment-integration-api/src/index.ts
  packages/payment-integration-api/src/util-types/guard.spec.ts
  packages/payment-integration-api/src/util-types/guard.ts
  packages/payment-integration-api/src/util-types/index.ts
  packages/payment-integrations-test-utils/src/test-utils/payment-integration-service.mock.ts
  packages/squarev2-integration/.eslintrc.json
  packages/squarev2-integration/README.md
  packages/squarev2-integration/jest.config.js
  packages/squarev2-integration/project.json
  packages/squarev2-integration/src/create-squarev2-payment-strategy.spec.ts
  packages/squarev2-integration/src/create-squarev2-payment-strategy.ts
  packages/squarev2-integration/src/index.ts
  packages/squarev2-integration/src/is-squarev2-window.ts
  packages/squarev2-integration/src/mocks/squarev2-method.mock.ts
  packages/squarev2-integration/src/mocks/squarev2-web-payments-sdk.mock.ts
  packages/squarev2-integration/src/squarev2-payment-initialize-options.ts
  packages/squarev2-integration/src/squarev2-payment-processor.spec.ts
  packages/squarev2-integration/src/squarev2-payment-processor.ts
  packages/squarev2-integration/src/squarev2-payment-strategy.spec.ts
  packages/squarev2-integration/src/squarev2-payment-strategy.ts
  packages/squarev2-integration/src/squarev2-script-loader.spec.ts
  packages/squarev2-integration/src/squarev2-script-loader.ts
  packages/squarev2-integration/src/types.ts
  packages/squarev2-integration/tsconfig.json
  packages/squarev2-integration/tsconfig.lib.json
  packages/squarev2-integration/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: integrations, sydney, reviewed, ready to merge, important
