Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-01, with the labels that each got.

#1310 fix(payment): ADYEN-296 Card fields validation
  src/payment/strategies/adyenv2/adyenv2-initialize-options.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
  src/payment/strategies/adyenv2/adyenv2.mock.ts
  src/payment/strategies/adyenv2/adyenv2.ts
Labels: sydney, in progress

#1317 fix(payments): ADYEN-373 fix iDEAL payment
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
  src/payment/strategies/adyenv2/adyenv2.ts
Labels: bug, sydney, qa pending, important

#1295 feat(payment): INT-5031 Stripe: Stripe UPE boilerplate
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/payment.ts
  src/payment/strategies/stripe-upe/index.ts
  src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe-script-loader.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-script-loader.ts
  src/payment/strategies/stripe-upe/stripe-upe.mock.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1313 feat(payment): PAYPAL-1208 renamed paypal Fields to PaymentFields
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-processor.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.spec.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-payment-strategy.ts
  src/payment/strategies/paypal-commerce/paypal-commerce-sdk.ts
  src/payment/strategies/paypal-commerce/paypal-commerce.mock.ts
Labels: sydney

#1318 feat(payment): BOLT-135 multi-field component
  src/payment/strategies/bolt/bolt-payment-strategy.ts
  src/payment/strategies/bolt/bolt.ts
Labels: sydney

#1290 test(payment): INT-4929 increase code coverage for GooglePayProcessor
  src/payment/strategies/googlepay/googlepay-payment-processor.spec.ts
Labels: integrations, reviewed, ready to merge

#1319 fix(payment): INT-5402 Afterpay - Change the SDK URL to the newest one
  src/payment/strategies/afterpay/afterpay-script-loader.spec.ts
  src/payment/strategies/afterpay/afterpay-script-loader.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1296 feat(payment): INT-5150 Delete experiment StripeV3 enable_reuse_payment_intent experiment
  src/payment/payment-methods.mock.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge
