Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-03, with the labels that each got.

#1349 feat(payment): INT-4970 Sagepay Stored Credit Cards
  src/payment/instrument/supported-payment-instruments.ts
Labels: integrations, reviewed, ready to merge

#1343 feat(checkout): ADYEN-378 AdyenV3 module creation
  src/payment/create-payment-strategy-registry.ts
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/adyenv3/adyenv3-initialize-options.ts
  src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
  src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
  src/payment/strategies/adyenv3/adyenv3-script-loader.spec.ts
  src/payment/strategies/adyenv3/adyenv3-script-loader.ts
  src/payment/strategies/adyenv3/adyenv3.mock.ts
  src/payment/strategies/adyenv3/adyenv3.ts
  src/payment/strategies/adyenv3/index.ts
Labels: sydney

#1367 fix(payment): INT-5645 Openpay: Change `OpyError` message
  src/payment/strategies/opy/opy-payment-error.spec.ts
  src/payment/strategies/opy/opy-payment-error.ts
  src/payment/strategies/opy/opy-payment-strategy.spec.ts
  src/payment/strategies/opy/opy-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1369 fixing deinitialize logic for mollie strategy
  src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  src/payment/strategies/mollie/mollie-payment-strategy.ts
Labels: integrations, sydney, reviewable, important

#1348 feat(payment): INT-5034 StripeUPE Add support for EPS
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1357 feat(payment): INT-5061 Stripe UPE localization
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/strategies/stripe-upe/format-locale.spec.ts
  src/payment/strategies/stripe-upe/format-locale.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe-supported-locales.ts
Labels: integrations, sydney, reviewed, ready to merge

#1350 INT-5040 [StripeUPE] Add GrabPay
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1371 fix(payment): INT-5723 StripeV3 fix vaulted cards with 3ds on
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1356 feat(payment): INT-5042 [Stripe UPE] Add support for Bancontact & iDeal
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1361 feat(payment): INT-5033 - INT-5053 [Stripe UPE] Add support for Giropay and Alipay
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1377 test(payment): INT-4928 Increase code coverage for GooglePayCheckoutCom
  src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts
Labels: integrations, sydney, reviewed, ready to merge

#1353 feat(payment): INT-5572 Stripe UPE Hide Fields
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1311 fix(payment): INT-5175 fixing redirect in googlepay using embedded checkout on customer section
  src/customer/strategies/googlepay/googlepay-customer-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1380 feat(checkout): ADYEN-399 AdyenV3 googlepay
  src/checkout-buttons/checkout-button-options.ts
  src/checkout-buttons/create-checkout-button-registry.spec.ts
  src/checkout-buttons/create-checkout-button-registry.ts
  src/checkout-buttons/strategies/checkout-button-method-type.ts
  src/checkout-buttons/strategies/googlepay/googlepay-adyenv3-button-strategy.spec.ts
  src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
  src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
  src/customer/create-customer-strategy-registry.ts
  src/customer/customer-request-options.ts
  src/customer/strategies/googlepay/googlepay-customer-method-type.ts
  src/customer/strategies/googlepay/googlepay-customer-mock.ts
  src/customer/strategies/googlepay/googlepay-customer-strategy.ts
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-request-options.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/googlepay/googlepay-adyenv3-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-adyenv3-initializer.ts
  src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.spec.ts
  src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  src/payment/strategies/googlepay/index.ts
Labels: sydney
