Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-09, with the labels that each got.

#1583 fix(payment): INT-6115 Payment with hosted credit card
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1578 fix(payment) INT-6328 Bluesnap open a new tab insted of using iframe to complete order
  packages/core/src/payment/strategies/bluesnapv2/bluesnapv2-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1530 feat(payment): INT-6310 added bank of new zealand strategy
  packages/core/src/payment/create-payment-strategy-registry.spec.ts
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/instrument/supported-payment-instruments.ts
  packages/core/src/payment/payment-strategy-type.ts
  packages/core/src/payment/strategies/bnz/bnz-payment-strategy.spec.ts
  packages/core/src/payment/strategies/bnz/bnz-payment-strategy.ts
  packages/core/src/payment/strategies/bnz/index.ts
Labels: integrations, sydney, reviewed, ready to merge

#1518 STRIPE-52 Auto-Select Address and mount shipping component for Stripe Link
  packages/core/src/customer/create-customer-strategy-registry.ts
  packages/core/src/customer/customer-request-options.ts
  packages/core/src/customer/strategies/stripe-upe/index.ts
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.spec.ts
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.ts
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer.mock.ts
  packages/core/src/customer/strategies/stripe-upe/stripeupe-customer-initialize-options.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-script-loader.spec.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-script-loader.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
  packages/core/src/shipping/create-shipping-strategy-registry.ts
  packages/core/src/shipping/shipping-request-options.ts
  packages/core/src/shipping/strategies/stripe-upe/index.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-initialize-options.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
Labels: integrations, sydney, reviewed, ready to merge

#1584 feat(payment): INT-5494 Worldpayaccess - Support vaulting
  packages/core/src/payment/instrument/supported-payment-instruments.ts
Labels: integrations, sydney, ready to merge, important

#1576 fix(payment): STRIPE-106 Added a catch in case an exception occurs when confirming the payment using 3DS2
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1609 fix(payment): ADYEN-545 bumped adyen-web version
  packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3-script-loader.spec.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3-script-loader.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3.ts
  packages/core/src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.ts
Labels: sydney

#1588 INT-6554 Worldpay Access - Increase code coverage
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.spec.ts
  packages/core/src/payment/strategies/worldpayaccess/worldpayaccess-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1586 fix(payment): STRIPE-131 Added a catch in case an exception occurs when confirming the payment using 3DS2
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1616 feat(payment): STRIPE-25 Stripe Link State
  packages/core/src/customer/customer-actions.ts
  packages/core/src/customer/customer-reducer.spec.ts
  packages/core/src/customer/customer-reducer.ts
  packages/core/src/customer/customer.ts
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.spec.ts
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.ts
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer.mock.ts
  packages/core/src/customer/strategies/stripe-upe/stripeupe-customer-initialize-options.ts
Labels: integrations, sydney, reviewable, important
