Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-12, with the labels that each got.

#1690 fix(payment): STRIPE-160 Fixed no order created for successful Stripe payment
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1688 feat(payment): INT-6727 add Klarna support for greece
  packages/core/src/payment/strategies/klarnav2/klarna-supported-countries.ts
Labels: integrations, mexico, reviewable, qa pending

#1702 fix(payment): INT-6928 [Mollie] No Ability To Use A Different Card To Pay
  packages/core/src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  packages/core/src/payment/strategies/mollie/mollie-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1662 feat(payment): STRIPE-178 Render Submit button after Stripe elements are loaded
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1696 feat(payment): INT-6957 Sezzle - Use window.location.replace to redirect
  packages/external-integration/project.json
  packages/external-integration/src/create-external-payment-strategy.ts
  packages/external-integration/src/external-payment-strategy.ts
  packages/external-integration/src/index.ts
  packages/sezzle-integration/.eslintrc.json
  packages/sezzle-integration/README.md
  packages/sezzle-integration/jest.config.js
  packages/sezzle-integration/project.json
  packages/sezzle-integration/src/create-sezzle-payment-strategy.spec.ts
  packages/sezzle-integration/src/create-sezzle-payment-strategy.ts
  packages/sezzle-integration/src/index.spec.ts
  packages/sezzle-integration/src/index.ts
  packages/sezzle-integration/src/sezzle-payment-strategy.spec.ts
  packages/sezzle-integration/src/sezzle-payment-strategy.ts
  packages/sezzle-integration/tsconfig.json
  packages/sezzle-integration/tsconfig.lib.json
  packages/sezzle-integration/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: integrations, sydney, reviewed, ready to merge, important

#1747 fix(payment): STRIPE-281 Fixed error when making purchases with only digital products
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Labels: integrations, sydney, reviewable
