Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-04, with the labels that each got.

#1378 fix(checkout): INT-5543 [CKO] Update to 3ds on Googlepay
  src/payment/create-payment-strategy-registry.ts
  src/payment/strategies/checkoutcom/checkoutcom-token.ts
  src/payment/strategies/googlepay/googlepay-adyenv2-payment-processor.ts
  src/payment/strategies/googlepay/googlepay-adyenv3-payment-processor.ts
  src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.spec.ts
  src/payment/strategies/googlepay/googlepay-checkoutcom-initializer.ts
  src/payment/strategies/googlepay/googlepay-checkoutcom-payment-processor.spec.ts
  src/payment/strategies/googlepay/googlepay-checkoutcom-payment-processor.ts
  src/payment/strategies/googlepay/googlepay-payment-processor.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.spec.ts
  src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  src/payment/strategies/googlepay/googlepay.ts
  src/payment/strategies/googlepay/index.ts
Labels: integrations, reviewed, ready to merge, important

#1370 feat(payment): INT-5057 STRIPE UPE use vaulted card
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.mock.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1359 feat(checkout): INT-5126 [MPGS] Add 3DS support to MPGS
  src/payment/create-payment-strategy-registry.spec.ts
  src/payment/create-payment-strategy-registry.ts
  src/payment/instrument/supported-payment-instruments.ts
  src/payment/payment-methods.mock.ts
  src/payment/payment-response-body.ts
  src/payment/payment-strategy-type.ts
  src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.spec.ts
  src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.ts
  src/payment/strategies/cba-mpgs/cba-mpgs-script-loader.spec.ts
  src/payment/strategies/cba-mpgs/cba-mpgs-script-loader.ts
  src/payment/strategies/cba-mpgs/cba-mpgs.mock.ts
  src/payment/strategies/cba-mpgs/cba-mpgs.ts
  src/payment/strategies/cba-mpgs/index.ts
Labels: integrations, reviewed, ready to merge, important

#1395 feat(payment): INT-5498 add detach function to deinitialize
  src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  src/payment/strategies/mollie/mollie-payment-strategy.ts
  src/payment/strategies/moneris/moneris-payment-strategy.spec.ts
  src/payment/strategies/moneris/moneris-payment-strategy.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1382 feat(payment): INT-5060 Stripe UPE Look and Feel - map theme styles to stripe appearance API
  src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  src/payment/strategies/stripe-upe/stripe-upe.mock.ts
  src/payment/strategies/stripe-upe/stripe-upe.ts
Labels: integrations, sydney, reviewed, ready to merge

#1399 feat(payment): INT-5573 Add shopper locale to Mollie strategy
  src/payment/payment-methods.mock.ts
  src/payment/payment.ts
  src/payment/strategies/mollie/mollie-payment-strategy.spec.ts
  src/payment/strategies/mollie/mollie-payment-strategy.ts
  src/payment/strategies/mollie/mollie.mock.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1397 fix(payment): INT-5821 Error on the Checkout related to Hide some fields using APM's
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1409 fix(checkout): ADYEN-431 AdyenV3 component state fix
  src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
  src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
  src/payment/strategies/adyenv3/adyenv3.mock.ts
  src/payment/strategies/adyenv3/adyenv3.ts
Labels: sydney

#1352 feat(checkout): INT-5273 Non-Default Shipping Method Selection On Cart Page Is Not Persisted to Apple Pay
  src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.spec.ts
  src/checkout-buttons/strategies/apple-pay/apple-pay-button-strategy.ts
  src/customer/strategies/apple-pay/apple-pay-customer-strategy.spec.ts
  src/customer/strategies/apple-pay/apple-pay-customer-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge
