Repository bigcommerce/checkout-sdk-js, pull requests merged in 2022-05, with the labels that each got.

#1385 feat(payment): INT-5754 Stripe UPE update payment intent
  src/payment/strategies/stripe-upe/stripe-upe-initialize-options.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.spec.ts
  src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1435 feat(checkout): INT-5963 Check for feature flag when loading threeDS Script
  src/payment/payment-methods.mock.ts
  src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.spec.ts
  src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.ts
Labels: integrations, reviewed, ready to merge, important

#1428 fix(checkout): IINT-5126 [MPGS] Add delay between calls for 3ds
  packages/core/src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.spec.ts
  packages/core/src/payment/strategies/cba-mpgs/cba-mpgs-payment-strategy.ts
Labels: integrations, sydney, reviewable, qa pending

#1431 fix(payment): INT-5949 Stripe UPE Don't hide state field
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
Labels: integrations, sydney, reviewable, important

#1449 fix(checkout): ADYEN-480 adyen vaulting fix
  packages/core/src/payment/payment.ts
  packages/core/src/payment/strategies/adyenv2/adyenv2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/adyenv2/adyenv2-payment-strategy.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.spec.ts
  packages/core/src/payment/strategies/adyenv3/adyenv3-payment-strategy.ts
Labels: sydney

#1434 fix(payment): INT-5826 AmazonPayV2: Provide a relative URL
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.spec.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-strategy.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge
