Repository bigcommerce/checkout-sdk-js, pull requests merged in 2023-05, with the labels that each got.

#1958 feat(payment): PAYPAL-2013 fixed braintree paylater button
  packages/braintree-integration/src/braintree-integration-service.ts
  packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.spec.ts
  packages/braintree-integration/src/braintree-paypal/braintree-paypal-customer-strategy.ts
  packages/braintree-integration/src/braintree.ts
  packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-button-strategy.ts
  packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/braintree/braintree-paypal-credit-button-strategy.ts
  packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.spec.ts
  packages/core/src/customer/strategies/braintree/braintree-paypal-credit-customer-strategy.ts
  packages/core/src/payment/strategies/braintree/braintree-sdk-creator.ts
  packages/core/src/payment/strategies/braintree/braintree.ts
Labels: sydney

#1971 feat(payment): INT-7516 SquareV2: Throw a `PaymentExecuteError` if tokenization fails
  packages/core/src/payment/errors/index.ts
  packages/core/src/payment/strategies/humm/humm-payment-strategy.spec.ts
  packages/core/src/payment/strategies/humm/humm-payment-strategy.ts
  packages/payment-integration-api/src/errors/index.ts
  packages/payment-integration-api/src/errors/payment-execute-error.spec.ts
  packages/payment-integration-api/src/errors/payment-execute-error.ts
  packages/payment-integration-api/src/index.ts
  packages/squarev2-integration/src/squarev2-payment-processor.spec.ts
  packages/squarev2-integration/src/squarev2-payment-processor.ts
Labels: integrations, sydney, reviewable, important

#1966 feat(payment): INT-7573 Create Access Worldpay GooglePay strategy
  packages/core/src/checkout-buttons/checkout-button-options.ts
  packages/core/src/checkout-buttons/create-checkout-button-registry.spec.ts
  packages/core/src/checkout-buttons/create-checkout-button-registry.ts
  packages/core/src/checkout-buttons/strategies/checkout-button-method-type.ts
  packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button-strategy.ts
  packages/core/src/checkout-buttons/strategies/googlepay/googlepay-button.mock.ts
  packages/core/src/checkout-buttons/strategies/googlepay/googlepay-worldpay-access-button-strategy.spec.ts
  packages/core/src/customer/create-customer-strategy-registry.ts
  packages/core/src/customer/customer-request-options.ts
  packages/core/src/customer/strategies/googlepay/googlepay-customer-method-type.ts
  packages/core/src/customer/strategies/googlepay/googlepay-customer-mock.ts
  packages/core/src/customer/strategies/googlepay/googlepay-customer-strategy.ts
  packages/core/src/customer/strategies/googlepay/googlepay-worldpayaccess-customer-strategy.spec.ts
  packages/core/src/payment/create-payment-strategy-registry.spec.ts
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/payment-request-options.ts
  packages/core/src/payment/payment-strategy-type.ts
  packages/core/src/payment/strategies/googlepay/googlepay-payment-strategy.ts
  packages/core/src/payment/strategies/googlepay/googlepay-worldpay-access-initializar.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-worldpay-access-initializer.ts
  packages/core/src/payment/strategies/googlepay/googlepay.mock.ts
  packages/core/src/payment/strategies/googlepay/index.ts
Labels: integrations, sydney, reviewed, qa pending, important
