Repository bigcommerce/checkout-sdk-js, pull requests merged in 2023-03, with the labels that each got.

#1881 fix(provider): INT-7463 Fixed problem with cards vaulted with 3ds in the hosted form flow
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1811 feat(payment): INT-7044 BlueSnapDirect: Add payment strategy for credit card
  .github/CODEOWNERS
  packages/bluesnap-direct-integration/.eslintrc.json
  packages/bluesnap-direct-integration/README.md
  packages/bluesnap-direct-integration/jest.config.js
  packages/bluesnap-direct-integration/project.json
  packages/bluesnap-direct-integration/src/bluesnap-direct-constants.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.spec.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-credit-card-payment-strategy.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.spec.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-form.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-input-validator.spec.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-hosted-input-validator.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-name-on-card-input.spec.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-name-on-card-input.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-script-loader.spec.ts
  packages/bluesnap-direct-integration/src/bluesnap-direct-script-loader.ts
  packages/bluesnap-direct-integration/src/create-bluesnap-direct-credit-card-payment-strategy.spec.ts
  packages/bluesnap-direct-integration/src/create-bluesnap-direct-credit-card-payment-strategy.ts
  packages/bluesnap-direct-integration/src/index.ts
  packages/bluesnap-direct-integration/src/is-array-of-allowed-props.ts
  packages/bluesnap-direct-integration/src/is-hosted-card-field-options-map.ts
  packages/bluesnap-direct-integration/src/mocks/bluesnap-direct-method.mock.ts
  packages/bluesnap-direct-integration/src/mocks/bluesnap-direct-sdk.mock.ts
  packages/bluesnap-direct-integration/src/mocks/credit-card-payment-initialize-options.mock.ts
  packages/bluesnap-direct-integration/src/types.ts
  packages/bluesnap-direct-integration/tsconfig.json
  packages/bluesnap-direct-integration/tsconfig.lib.json
  packages/bluesnap-direct-integration/tsconfig.spec.json
  packages/payment-integration-api/src/payment/payment.ts
  tsconfig.base.json
  workspace.json
Labels: integrations, sydney, reviewed, ready to merge, important

#1882 feat(payment): PAYPAL-2006 Created paypal-express-integration Checkout sdk package
  .github/CODEOWNERS
  packages/paypal-express-integration/.eslintrc.json
  packages/paypal-express-integration/README.md
  packages/paypal-express-integration/jest.config.js
  packages/paypal-express-integration/project.json
  packages/paypal-express-integration/src/create-paypal-express-button-strategy.spec.ts
  packages/paypal-express-integration/src/create-paypal-express-button-strategy.ts
  packages/paypal-express-integration/src/index.ts
  packages/paypal-express-integration/src/mocks/paypal-express-mock.ts
  packages/paypal-express-integration/src/paypal-express-button-initialize-options.ts
  packages/paypal-express-integration/src/paypal-express-button-strategy.spec.ts
  packages/paypal-express-integration/src/paypal-express-button-strategy.ts
  packages/paypal-express-integration/src/paypal-express-script-loader.spec.ts
  packages/paypal-express-integration/src/paypal-express-script-loader.ts
  packages/paypal-express-integration/src/paypal-express-types.ts
  packages/paypal-express-integration/tsconfig.json
  packages/paypal-express-integration/tsconfig.lib.json
  packages/paypal-express-integration/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: sydney

#1914 feat(payment): PAYPAL-2004 added ability to change style for amazonpay button
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-options.ts
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.spec.ts
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button-strategy.ts
  packages/core/src/checkout-buttons/strategies/amazon-pay-v2/amazon-pay-v2-button.mock.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-processor.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2.ts
Labels: sydney
