Repository bigcommerce/checkout-sdk-js, pull requests merged in 2023-01, with the labels that each got.

#1701 feat(payment): INT-6729 add Klarna support for Czech Republic
  packages/core/src/payment/strategies/klarnav2/klarna-supported-countries.ts
Labels: enhancement, integrations, sydney, reviewed, ready to merge

#1765 fix(payment): INT-7103 SquareV2: Assume that `postalCode` is valid unless it changes
  .github/CODEOWNERS
  packages/squarev2-integration/src/mocks/squarev2-web-payments-sdk.mock.ts
  packages/squarev2-integration/src/squarev2-payment-processor.spec.ts
  packages/squarev2-integration/src/squarev2-payment-processor.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1700 refactor(payment): INT-6964 Sunset Amazon Pay V1
  packages/core/src/checkout/checkout-service.ts
  packages/core/src/customer/create-customer-strategy-registry.ts
  packages/core/src/customer/customer-request-options.ts
  packages/core/src/customer/strategies/amazon-pay-v2/amazon-pay-v2-customer-initialize-options.ts
  packages/core/src/customer/strategies/amazon/amazon-pay-customer-initialize-options.ts
  packages/core/src/customer/strategies/amazon/amazon-pay-customer-strategy.spec.ts
  packages/core/src/customer/strategies/amazon/amazon-pay-customer-strategy.ts
  packages/core/src/customer/strategies/amazon/index.ts
  packages/core/src/payment/create-payment-strategy-registry.spec.ts
  packages/core/src/payment/create-payment-strategy-registry.ts
  packages/core/src/payment/payment-methods.mock.ts
  packages/core/src/payment/payment-request-options.ts
  packages/core/src/payment/payment-strategy-action-creator.spec.ts
  packages/core/src/payment/payment-strategy-registry.spec.ts
  packages/core/src/payment/payment-strategy-type.ts
  packages/core/src/payment/strategies/amazon-pay-v2/amazon-pay-v2-payment-initialize-options.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-address-book.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-confirmation-flow.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-login-button.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-login.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-order-reference.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-payment-initialize-options.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.spec.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-payment-strategy.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-script-loader.spec.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-script-loader.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-wallet.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-widget-error.ts
  packages/core/src/payment/strategies/amazon-pay/amazon-pay-window.ts
  packages/core/src/payment/strategies/amazon-pay/index.ts
  packages/core/src/shipping/create-shipping-strategy-registry.spec.ts
  packages/core/src/shipping/create-shipping-strategy-registry.ts
  packages/core/src/shipping/shipping-request-options.ts
  packages/core/src/shipping/strategies/amazon-pay-v2/amazon-pay-v2-shipping-initialize-options.ts
  packages/core/src/shipping/strategies/amazon/amazon-pay-shipping-initialize-options.ts
  packages/core/src/shipping/strategies/amazon/amazon-pay-shipping-strategy.spec.ts
  packages/core/src/shipping/strategies/amazon/amazon-pay-shipping-strategy.ts
  packages/core/src/shipping/strategies/amazon/index.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1760 feat(payment): STRIPE-194 Clear Prefilled Shipping Address Information If Shopper Logs Out Of Link
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
Labels: integrations, sydney, ready to merge
