Repository bigcommerce/checkout-sdk-js, pull requests merged in 2023-02, with the labels that each got.

#1763 feat(payment): STRIPE-289 Loading Submit button after card loads
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-payment-strategy.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.mock.ts
Labels: integrations, sydney, reviewable

#1779 fix(payment): STRIPE-287 Fixed error when using vaulted card L2/L3 field appear as null on dashboard
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.spec.ts
  packages/core/src/payment/strategies/stripev3/stripev3-payment-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1809 feat(payment): PAYPAL-1634 added ability for applepay spb to work with buyNowCart on PDP
  packages/apple-pay-integration/src/apple-pay-button-initialize-options.ts
  packages/apple-pay-integration/src/apple-pay-button-strategy.spec.ts
  packages/apple-pay-integration/src/apple-pay-button-strategy.ts
  packages/apple-pay-integration/src/mocks/apple-pay-button.mock.ts
  packages/apple-pay-integration/src/mocks/apple-pay-payment.mock.ts
Labels: sydney

#1810 feat(payment): INT-7044 BlueSnapDirect: Pass options to `loadPaymentMethod`
  packages/core/src/payment-integration/default-payment-integration-service.spec.ts
  packages/core/src/payment-integration/default-payment-integration-service.ts
  packages/payment-integration-api/src/payment-integration-service.ts
Labels: integrations, sydney, reviewed, ready to merge, important

#1681 feat(payment): STRIPE-200 add stripe phone field
  packages/core/src/payment/strategies/stripe-upe/stripe-upe-script-loader.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping.mock.ts
Labels: integrations, sydney, reviewed, ready to merge

#1869 fix(payment): PAYPAL-1993 make StripeUPE Google Pay compatible with Buy Now cart
  packages/core/src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-stripe-upe-initializer.ts
Labels: sydney

#1862 fix(payment): PAYPAL-1997 make CyberSourceV2 Google Pay compatible with Buy Now cart
  packages/core/src/payment/strategies/googlepay/googlepay-cybersourcev2-initializer.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-cybersourcev2-initializer.ts
Labels: sydney

#1867 fix(payment): PAYPAL-1998 make Orbital Google Pay compatible with Buy Now cart
  packages/core/src/payment/strategies/googlepay/googlepay-orbital-initializer.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-orbital-initializer.ts
Labels: sydney

#1870 fix(payment): PAYPAL-1999 make Stripe Google Pay compatible with BuyNow cart
  packages/core/src/payment/strategies/googlepay/googlepay-stripe-initializer.spec.ts
  packages/core/src/payment/strategies/googlepay/googlepay-stripe-initializer.ts
Labels: sydney

#1833 feat(payment): INT-6312 klarnav2 increase code coverage
  packages/core/src/payment/strategies/klarnav2/klarnav2-payment-strategy.spec.ts
  packages/core/src/payment/strategies/klarnav2/klarnav2.mock.ts
Labels: integrations, sydney, reviewed, ready to merge

#1675 fix(shipping): STRIPE-202 Split name input into First and Last name
  packages/core/src/customer/strategies/stripe-upe/stripe-upe-customer-strategy.ts
  packages/core/src/payment/strategies/stripe-upe/stripe-upe.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.spec.ts
  packages/core/src/shipping/strategies/stripe-upe/stripe-upe-shipping-strategy.ts
Labels: integrations, sydney, reviewed, ready to merge

#1873 feat(payment): PAYPAL-1985 added loadDefaultCheckout onCancel to avoid potential errors
  packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.spec.ts
  packages/paypal-commerce-integration/src/paypal-commerce-alternative-methods/paypal-commerce-alternative-methods-button-strategy.ts
  packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.spec.ts
  packages/paypal-commerce-integration/src/paypal-commerce-credit/paypal-commerce-credit-button-strategy.ts
  packages/paypal-commerce-integration/src/paypal-commerce-types.ts
  packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.spec.ts
  packages/paypal-commerce-integration/src/paypal-commerce-venmo/paypal-commerce-venmo-button-strategy.ts
  packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.spec.ts
  packages/paypal-commerce-integration/src/paypal-commerce/paypal-commerce-button-strategy.ts
Labels: sydney
